version: '3.8'

services:
  emqx:
    image: emqx:5.3
    container_name: emqx
    ports:
      - 1883:1883
      - 18083:18083
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node.emqx.io
    networks:
      - localnet

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.9
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - localnet

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.5
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9091,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
