version: '3.8'

services:
  redis:
    container_name: redis
    image: bitnami/redis:7.2
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - localnet

  minio:
    container_name: minio
    image: bitnami/minio:2023
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - localnet

  cassandra:
    container_name: cassandra
    image: bitnami/cassandra:4.1
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD_SEEDER=
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
