version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - localnet

  kibana:
    image: bitnami/kibana:8.10.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
