version: '3.8'

services:
  structurizr:
    image: structurizr/lite:latest
    container_name: structurizr
    ports:
      - 8080:8080
    volumes:
      - ../:/usr/local/structurizr
    networks:
      - platform

networks:
  localnet:
    driver: bridge
